name: CI/CD using Github Actions

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # JDK setting - github actions에서 사용할 JDK 설정 (프로젝트나 AWS의 java 버전과 달라도 무방)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # gradle caching - 빌드 시간 향상
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      # 서비스에 필요한 yml 파일 생성
      # application-db.yml 생성
      - name: Make application-db.yml
        if: |
          contains(github.ref, 'develop')
        run: |
          cd ./src/main/resources
          touch ./application-db.yml
          echo ${{ secrets.YML_DEV_DB }} | base64 --decode > ./application-db.yml
        shell: bash

      # application-file.yml 생성
      - name: Make application-file.yml
        if: |
          contains(github.ref, 'develop')
        run: |
          cd ./src/main/resources
          touch ./application-file.yml
          echo ${{ secrets.YML_DEV_FILE }} | base64 --decode > ./application-file.yml
        shell: bash

      # application-jwt.yml 생성
      - name: Make application-jwt.yml
        if: |
          contains(github.ref, 'develop')
        run: |
          cd ./src/main/resources
          touch ./application-jwt.yml
          echo ${{ secrets.YML_DEV_JWT }} | base64 --decode > ./application-jwt.yml
        shell: bash

      # Gradle에 실행 권한을 부여
      - name: Grant execute permission for gradlew
        run: chmod 777 ./gradlew

      # Gradle로 clean build
      - name: Build with Gradle
        run: ./gradlew clean build

      # DockerHub에 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Docker image 빌드
      - name: Build Docker
        run: docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/freshmate .

      # DuckerHub에 Push
      - name: Push Docker
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/freshmate:latest
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # deploy.sh 파일 서버로 전달하기(복사 후 붙여넣기)
#      - name: Send deploy.sh
#        uses: appleboy/scp-action@master
 #       with:
 #         username: ubuntu
 #         host: ${{ secrets.FRESHMATE_IP }}
 #         key: ${{ secrets.EC2_SSH_KEY }}
 #         port: 22
 #         source: "./deploy.sh"
 #         target: "/home/ubuntu/"

      # 도커 허브에서 jar파일 및 pull후에 컴포즈 up
      - name: Deploy to Dev
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.FRESHMATE_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/freshmate:latest
            chmod 777 ./deploy.sh
            ./deploy.sh
            docker image prune -f
    
#      - name: Set target IP
#        run: |
#          STATUS=$(curl -o /dev/null -w "%{http_code}" "http://${{ secrets.FRESHMATE_IP }}/env")
#          echo $STATUS
#          if [ $STATUS = 200 ]; then
#            CURRENT_UPSTREAM=$(curl -s "http://${{ secrets.FRESHMATE_IP }}/env")
#          else
#            CURRENT_UPSTREAM=green
#          fi
#          echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
#          if [ $CURRENT_UPSTREAM = blue ]; then
#            echo "CURRENT_PORT=8080" >> $GITHUB_ENV
#            echo "STOPPED_PORT=8081" >> $GITHUB_ENV
#            echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
#          elif [ $CURRENT_UPSTREAM = green ]; then
#            echo "CURRENT_PORT=8081" >> $GITHUB_ENV
#            echo "STOPPED_PORT=8080" >> $GITHUB_ENV
#            echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
#          else
#            echo "error"
#            exit 1
#          fi
#          
#      - name: Docker compose
#        uses: appleboy/ssh-action@master
#        with:
#          username: ubuntu
#          host: ${{ secrets.FRESHMATE_IP }}
#          key: ${{ secrets.EC2_SSH_KEY }}
#          script_stop: true
#          script: |
#            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/freshmate:latest
#            sudo docker-compose -f docker-compose-${{env.TARGET_UPSTREAM}}.yml up -d
#      
#      - name: Check deploy server URL
#        uses: jtalk/url-health-check-action@v3
#        with:
#          url: http://${{ secrets.FRESHMATE_IP }}:${{env.STOPPED_PORT}}/env
#          max-attempts: 5
#          retry-delay: 10s
#
#      - name: Change nginx upstream
#        uses: appleboy/ssh-action@master
#        with:
#          username: ubuntu
#          host: ${{ secrets.FRESHMATE_IP }}
#          key: ${{ secrets.EC2_SSH_KEY }}
#          script_stop: true
#          script: |
#            sudo docker exec -i nginxserver bash -c 'echo "set \$service_url ${{ env.TARGET_UPSTREAM }};" > /etc/nginx/conf.d/service-env.inc && nginx -s reload' 
#
#      - name: Stop current server
#        uses: appleboy/ssh-action@master
#        with:
#          username: ubuntu
#          host: ${{ secrets.FRESHMATE_IP }}
#          key: ${{ secrets.EC2_SSH_KEY }}
#          script_stop: true
#          script: |
#            sudo docker stop ${{env.CURRENT_UPSTREAM}}
#            sudo docker rm ${{env.CURRENT_UPSTREAM}}
